server:
    port: 8081
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db
        username: sa
        password: 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true